-- DDL for prod.lessons
CREATE TABLE prod.lessons (
    id           SERIAL PRIMARY KEY,
    last_updated TIMESTAMP NOT NULL DEFAULT NOW(),
    file_name    VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL
);

-- Add broad_area column
ALTER TABLE prod.lessons
    ADD COLUMN broad_area VARCHAR(100);

-- Inserts
INSERT INTO prod.lessons (file_name, display_name, broad_area) VALUES
('AdditionusingEquivalentFractions', 'Addition Using Equivalent Fractions', 'FDRRP'),
('AnalyticalGeometry-SlopeInterceptEquation', 'Analytical Geometry: Slope-Intercept Equation', 'Analytical Geometry'),
('AnalyticalGeometry-Slopeofaline', 'Analytical Geometry: Slope of a Line', 'Analytical Geometry'),
('Angles-1', 'Angles 1', 'Geometry'),
('Angles-2', 'Angles 2', 'Geometry'),
('Area-TriangleandParallelogram', 'Area of Triangles and Parallelograms', 'Measurement'),
('AreaandPerimeterofTrapezoid', 'Area and Perimeter of a Trapezoid', 'Measurement'),
('AreaOfCompositeShapes', 'Area of Composite Shapes', 'Measurement'),
('AreaofSquaresandRectangles', 'Area of Squares and Rectangles', 'Measurement'),
('BasicRounding', 'Basic Rounding', 'Number Sense'),
('BeforeLongDivision', 'Before Long Division', 'Number Sense'),
('BenchmarkPercents', 'Benchmark Percents', 'FDRRP'),
('BinomialProduct', 'Binomial Product', 'HS Algebra'),
('CalculatingFractionofaQuantity', 'Calculating a Fraction of a Quantity', 'FDRRP'),
('Circle-1', 'Circle 1', 'Geometry'),
('Circle-2', 'Circle 2', 'Geometry'),
('ComparingAndOrderingDecimal', 'Comparing and Ordering Decimals', 'FDRRP'),
('ComparingFraction-Part1', 'Comparing Fractions: Part 1', 'FDRRP'),
('ComparingFractions-Part2', 'Comparing Fractions: Part 2', 'FDRRP'),
('ConceptOfArea', 'Concept of Area', 'Measurement'),
('ConvertingImproperFractionToMixedFraction', 'Converting Improper Fractions to Mixed Numbers', 'FDRRP'),
('ConvertingMixedFractionToImproperFraction', 'Converting Mixed Numbers to Improper Fractions', 'FDRRP'),
('Cylinder-VolumeandCapacity', 'Cylinder: Volume and Capacity', 'Measurement'),
('DecimalAddition', 'Decimal Addition', 'FDRRP'),
('DecimalMultiplicationByPowerof10', 'Decimal Multiplication by Powers of 10', 'FDRRP'),
('DecimalSubtraction', 'Decimal Subtraction', 'FDRRP'),
('DistributiveEquation', 'Distributive Equations', 'HS Algebra'),
('DistributiveProperty', 'Distributive Property', 'HS Algebra'),
('DividingDecimalBy10', 'Dividing Decimals by 10', 'FDRRP'),
('Divisionbypowerof10', 'Division by Powers of 10', 'FDRRP'),
('DivisionWordProblems-2', 'Division Word Problems 2', 'FDRRP'),
('EquationswithExponents', 'Equations with Exponents', 'Advance NS'),
('EquivalentDecimal', 'Equivalent Decimals', 'FDRRP'),
('EssentialCombinationsinTimesTable', 'Essential Combinations in the Times Table', 'Number Sense'),
('Exponents', 'Exponents', 'Advance NS'),
('FactorsandGCF', 'Factors and GCF', 'Advance NS'),
('FormingEquationfromWordProblems', 'Forming Equations from Word Problems', 'Algebra'),
('FractionAdditionwithUnlikeDenominator', 'Fraction Addition with Unlike Denominators', 'FDRRP'),
('FractionDivision-Introduction', 'Fraction Division: Introduction', 'FDRRP'),
('FractionEquation', 'Fraction Equations', 'Algebra'),
('FractionMultiplication-Introduction', 'Fraction Multiplication: Introduction', 'FDRRP'),
('FractionNamesTypes', 'Fraction Names and Types', 'FDRRP'),
('FractionOfaSet', 'Fraction of a Set', 'FDRRP'),
('FractionontheNumberLine', 'Fractions on the Number Line', 'FDRRP'),
('FractionSubtractionwithUnlikeDenominator', 'Fraction Subtraction with Unlike Denominators', 'FDRRP'),
('FractionwithWholeNumber', 'Fractions with Whole Numbers', 'FDRRP'),
('FractionWordProblems', 'Fraction Word Problems', 'FDRRP'),
('GeneratingEquivalentFraction', 'Generating Equivalent Fractions', 'FDRRP'),
('Inequalities', 'Inequalities', 'Algebra'),
('InputOuput', 'Input and Output', 'Algebra'),
('IntegerAdd-Subtract-Chainofintegers', 'Integer Addition and Subtraction: Chain of Integers', 'Algebra'),
('IntegerAdd-Subtract-CombineSignedNumbers', 'Integer Addition and Subtraction: Combining Signed Numbers', 'Algebra'),
('Integers-AdditionSubtraction', 'Integers: Addition and Subtraction', 'Algebra'),
('Integers-AnIntroduction', 'Integers: An Introduction', 'Algebra'),
('Integers-Division', 'Integers: Division', 'Algebra'),
('Integers-Multiplication', 'Integers: Multiplication', 'Algebra'),
('IntroductiontoDecimals', 'Introduction to Decimals', 'FDRRP'),
('IntroductiontoEquations', 'Introduction to Equations', 'Algebra'),
('IntroductiontoExpressionsandEquations', 'Introduction to Expressions and Equations', 'Algebra'),
('IntroductiontoFactorization', 'Introduction to Factorization', 'HS Algebra'),
('IntroductiontoPercent', 'Introduction to Percent', 'FDRRP'),
('IntroductionToPolynomials', 'Introduction to Polynomials', 'HS Algebra'),
('J-DifferenceofSquares', 'Difference of Squares', 'HS Algebra'),
('LinearEquations-WordProblem', 'Linear Equations: Word Problems', 'Algebra'),
('LongDivision-1', 'Long Division 1', 'Number Sense'),
('LongDivision-2', 'Long Division 2', 'Number Sense'),
('MultiplesandLCM', 'Multiples and LCM', 'Advance NS'),
('MultiplicationByPowerof10', 'Multiplication by Powers of 10', 'Number Sense'),
('MultiplyingMultiplesofTen', 'Multiplying Multiples of Ten', 'Number Sense'),
('NegativeExponents', 'Negative Exponents', 'Advance NS'),
('NumberPattern-2steppatterns', 'Number Patterns: Two-Step Patterns', 'Algebra'),
('NumberPatterns-Introduction', 'Number Patterns: Introduction', 'Algebra'),
('NumberPatternswithIntegers', 'Number Patterns with Integers', 'Algebra'),
('Percent', 'Percent', 'FDRRP'),
('PercentOnNumberLine', 'Percent on a Number Line', 'FDRRP'),
('Perimeter', 'Perimeter', 'Measurement'),
('PerimeterandPerimeter-SideRelationship', 'Perimeter and Side Length Relationships', 'Measurement'),
('PrimeFactorization', 'Prime Factorization', 'Advance NS'),
('PrimeNumbers', 'Prime Numbers', 'Advance NS'),
('PythagorasTheorem', 'Pythagoras'' Theorem', 'Measurement'),
('Ratio', 'Ratio', 'FDRRP'),
('Ratio-BasicExamples', 'Ratio: Basic Examples', 'FDRRP'),
('RearrangeEquationorFormulaandEvaluate', 'Rearranging Equations and Formulas to Evaluate', 'HS Algebra'),
('ReducingFraction', 'Reducing Fractions', 'FDRRP'),
('RelationbetweenAreaandPerimeter', 'Relationship Between Area and Perimeter', 'Measurement'),
('RoundingDecimal', 'Rounding Decimals', 'FDRRP'),
('SolvingEquation-InverseOperation', 'Solving Equations Using Inverse Operations', 'Algebra'),
('SolvingEquation-MovingacrossEqualtosign', 'Solving Equations by Moving Across the Equal Sign', 'Algebra'),
('SolvingEquations', 'Solving Equations', 'Algebra'),
('SquareAndSquareRoots', 'Squares and Square Roots', 'Advance NS'),
('SquareCubicUnitConversions', 'Square and Cubic Unit Conversions', 'Measurement'),
('SubtractionusingEquivalentFractions', 'Subtraction Using Equivalent Fractions', 'FDRRP'),
('SurfaceAreaofaCone', 'Surface Area of a Cone', 'Measurement'),
('SurfaceAreaofaCylinder', 'Surface Area of a Cylinder', 'Measurement'),
('SurfaceAreaofaTriangularPrism', 'Surface Area of a Triangular Prism', 'Measurement'),
('TargetinganEquivalentFraction', 'Targeting an Equivalent Fraction', 'FDRRP'),
('UnitFractionOfASet', 'Unit Fraction of a Set', 'FDRRP'),
('UnitRateandUnitaryMethod', 'Unit Rate and Unitary Method', 'FDRRP'),
('VolumeCapacityUnits', 'Volume and Capacity Units', 'Measurement'),
('VolumeofRectangularPrism', 'Volume of a Rectangular Prism', 'Measurement'),
('VolumeofTriangularPrism', 'Volume of a Triangular Prism', 'Measurement');
